FROM ubuntu:jammy@sha256:b8b6ee6aa931ecd9d0d952abc34dc0e5f7c6a30c6bb71b079fe399fde0329c02

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update -qq \
 && apt-get install -qq -y --no-install-recommends \
    git ca-certificates build-essential devscripts debhelper cmake \
    equivs fakeroot dpkg-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY build.sh /build.sh
RUN chmod +x /build.sh

VOLUME /artifacts

ENTRYPOINT ["/build.sh"]
