FROM ubuntu:jammy@sha256:5ec03bb3441e8b0bf3b4f9cd4629a1ae763010dc3035bb8da3ae6cf026486401

ENV DEBIAN_FRONTEND=noninteractive

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN apt-get update -qq \
 && apt-get install -qq -y --no-install-recommends \
    git ca-certificates build-essential devscripts debhelper cmake \
    equivs fakeroot dpkg-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY build.sh /build.sh
RUN chmod +x /build.sh

VOLUME /artifacts

ENTRYPOINT ["/build.sh"]
