name: push-readme

on:
  push:
    paths:
      - 'README.md'
      - '.github/workflows/push-readme.yml'
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        module: [client, director, storage, webui, api]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
          repository: darkvex/bareos-${{ matrix.module }}
