name: Scan and upload sarif report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '15 23 * * 1'

permissions:
  contents: read

jobs:
  build:
    permissions:
      checks: write
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Image Scan
      id: scan
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      run: |
        curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
        chmod +x wizcli
        ./wizcli scan container-image ${IMAGE}:${TAG} --sarif-output-file=sarif.json

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v4
      #Upload SARIF file
      if: success() || failure()
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
