name: test-n-lint

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install hadolint
        run: |
          version=v2.15.1
          sha256=c7187db94eeeeca956519a6af171adc31453941a1e777961f6e680f697c8c507
          file='hadolint-linux-x86_64'
          url_rlz="https://github.com/hadolint/hadolint/releases/download/${version}"
          curl -fsSL -o "$file" "${url_rlz}/$file"
          echo "${sha256}  ${file}" | sha256sum -c -
          chmod u+x "$file"
          ln -s "$file" hadolint
      - name: Check Docker files
        run: |
          for file in $(find . -name Dockerfile); do
            ./hadolint --ignore DL3008 --ignore DL3018 --ignore DL3059 $file
          done

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install mardownlint
        run: |
          sudo apt-get install ruby-full 
          sudo gem install mdl

      - name: Check md files
        run: |
          for file in $(find . -name "*.md"); do
            mdl $file
          done
