FROM alpine:3.24

RUN apk add --no-cache alpine-sdk sudo bash git ca-certificates \
 && ln -s /var/cache/apk /etc/apk/cache \
 && apk update

RUN adduser -D builder \
 && addgroup builder abuild \
 && echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder \
 && chmod 0440 /etc/sudoers.d/builder \
 && mkdir -p /var/cache/distfiles \
 && chmod a+w /var/cache/distfiles

ENV ABUILD_KEY_NAME=bareos-apk@dark-vex.rsa
COPY keys/bareos-apk@dark-vex.rsa.pub /etc/apk/keys/bareos-apk@dark-vex.rsa.pub
COPY build.sh /build.sh
RUN chmod +x /build.sh

VOLUME /artifacts

ENTRYPOINT ["/build.sh"]
